global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 2m
  receiver: carp-webhook
receivers:
  - name: 'carp-webhook'
    webhook_configs:
      - url: 'http://host.docker.internal:8863/carp/api/carp/alert/webhook'
        send_resolved: true     # 表示服务恢复后会收到恢复告警
