# plugin boot class
plugin.boot.class=cn.sliew.carp.plugin.test.exp.HelloBoot
# plugin code
# Cannot be null
plugin.code=HelloBoot
# description
plugin.desc=this a plugin a v1 demo
# version
plugin.version=0.0.1