global:
  scrape_interval: 10s # 每 10s 采集一次数据
  evaluation_interval: 10s # 每 10s 检测一次告警

scrape_configs:
  - job_name: 'springboot'
    metrics_path: /carp/actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - 'host.docker.internal:8863'
        labels:
          group: 'spring-boot-metrics'

  - job_name: 'minio'
    metrics_path: /minio/prometheus/metrics/v3
    scheme: http
    static_configs:
      - targets:
          - 'host.docker.internal:9000'
        labels:
          group: 'minio-metrics'