global:
  scrape_interval: 30s # 每 30s 采集一次数据
  evaluation_interval: 10s # 每 10s 检测一次告警

scrape_configs:
  - job_name: 'springboot'
    metrics_path: /carp/actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - 'host.docker.internal:8863'
        labels:
          group: 'spring-boot-metrics'

  - job_name: 'minio-job'
    metrics_path: /minio/v2/metrics/cluster
    #    bearer_token: xxx 需要到容器内部生成。或者启用 MINIO_PROMETHEUS_AUTH_TYPE=public 环境变量
    scheme: http
    static_configs:
      - targets:
          - 'host.docker.internal:9000'
        labels:
          group: 'minio-metrics'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
          - 'host.docker.internal:9093'

rule_files:
  - /etc/prometheus/rules/*.yml