version: "3.8"

services:

  mongo:
    image: mongo:7.0.8
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - mongo

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/
      - ME_CONFIG_BASICAUTH=false
    ports:
      - 8081:8081
    restart: unless-stopped
    networks:
      - mongo

networks:
  mongo:
    driver: bridge