# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3.8"

services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.2.1
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    ports:
      - 9090:9090
    volumes:
      - ../prometheus/config.yml:/etc/prometheus/prometheus.yml
      - ../prometheus/rules:/etc/prometheus/rules
    networks:
      - alert

  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.115.0
    environment:
      - TZ=Asia/Shanghai
    command:
      - '--loggerTimezone=Asia/Shanghai'
    ports:
      - 8428:8428
    networks:
      - alert

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.28.1
    ports:
      - 9093:9093
    volumes:
      - ../alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - alert

  grafana:
    container_name: grafana
    image: grafana/grafana:11.6.0
    depends_on:
      - prometheus
    environment:
      - TZ=Asia/Shanghai
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    volumes:
      - ../grafana/config.ini:/etc/grafana/grafana.ini
      - ../grafana/dashboards:/var/lib/grafana/dashboards
      - ../grafana/plugins:/var/lib/grafana/plugins
      - ../grafana/provisioning:/etc/grafana/provisioning
    networks:
      - alert

  karma:
    container_name: karma
    image: ghcr.io/prymitive/karma:v0.121
    depends_on:
      - alertmanager
    environment:
      - TZ=Asia/Shanghai
      - ALERTMANAGER_URI=http://alertmanager:9093
    ports:
      - 8999:8080
    networks:
      - alert
#
#  nightingale:
#    image: flashcatcloud/nightingale:8.0.0-beta.10
#    container_name: nightingale
#    environment:
#      - TZ=Asia/Shanghai
#      - GIN_MODE=release
#      - WAIT_HOSTS=host.docker.internal:3306, host.docker.internal:6379
#    command: sh -c "/app/n9e"
#    depends_on:
#      - victoriametrics
#    volumes:
#      - ../nightingale:/app/etc
#    ports:
#      - 17000:17000
#      - 20090:20090
#    networks:
#      - alert

networks:
  alert:
    driver: bridge